- hosts: web_servers
  become: yes
  tasks:
    - name: copy files to webserver root directory
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

