---

- hosts: all
  become: yes 
  vars:
    proxy_var:
      http_proxy: "http://172.16.43.4:3128"
      https_proxy: "http://172.16.43.4:3128"
      no_proxy: "192.168.48.0/24,localhost,127.0.0.1"

  pre_tasks:
    #    - name: Update apt
    #  apt:
    #    update_cache: yes
    #    state: latest
    #  when: ansible_distribution in ["Debian", "Ubuntu"]
      # when: ansible_distribution == "Ubuntu" and "ansible_distribution_version" == "24.04"
      # we can see other information with #ansible all -m gather_facts commands
    - name: install update (CentOS)
      tags: always
      package:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CetnOS"

    - name: install update (Ubuntu)
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: yes
  tasks:
    - name: install apache2 and php
      tags: apache2,ubuntu
      environment: "{{proxy_var}}"
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
        dpkg_options: "--fix-missing"
      when: ansible_distribution == "Ubuntu"

    - name: install apache 2
      tags: centos,httpd
      environment: "{{proxy_var}}"
      dnf:
        name:
          - httpd
          - php
        update_cache: yes
      when: ansible_distribution == "CentOS"

