---

- hosts: all
  become: yes 
  vars:
    proxy_var:
      http_proxy: "http://172.16.43.4:3128"
      https_proxy: "http://172.16.43.4:3128"
      no_proxy: "192.168.48.0/24,localhost,127.0.0.1"

  tasks:
    #    - name: Update apt
    #  apt:
    #    update_cache: yes
    #    state: latest
    #  when: ansible_distribution in ["Debian", "Ubuntu"]
      # when: ansible_distribution == "Ubuntu" and "ansible_distribution_version" == "24.04"
      # we can see other information with #ansible all -m gather_facts commands
  
    - name: install apache2 and php
      environment: "{{proxy_var}}"
      apt:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
        dpkg_options: "--fix-missing"
